### ISSUE TITLE
Response is only OK

### ISSUE THREAD

**Issue by Iceman25** [adafruit/Adafruit_BluefruitLE_nRF51#10]
Hi,
I've worked with the Bluefruit LE Micro for quite a while, but now I am encountering some weird behaviour. 
I have set up a GATT Server with a characteristic which is 4 bytes long. I try to read the characteristic with 

``` C++
char buff[20];
  ble.print(F("AT+GATTCHAR="));
  ble.println(index, DEC);
  int count = ble.readline(BLE_DEFAULT_TIMEOUT,false);
  memcpy(buff,ble.buffer,min(count,20));
```

but the only response in buff is "OK"
I even tried to reproduce this with the atcommand sketch which succeeded to do so.

**Comment by microbuilder** [comment]
Can you please post this on the support forums in the Wireless forum with a link here and information such as the firmware you are running?  All of the support is handled through the forums, and the support staff doesn't monitor Github issues or get any email alerts from Github.
