### ISSUE TITLE
Example to Publish Analog PIN as Notify Characteristic

### ISSUE THREAD

**Issue by semireg** [adafruit/Adafruit_BluefruitLE_nRF51#15]
Is there an example of publishing an analog pin as a notify characteristic?

**Comment by microbuilder** [comment]
Not presently, no, but this is really a support issue so please post it in the Adafruit support forums (where the support team will actually see them).  Github issues are exclusively for pull requests and bugs with existing code.  Thanks!

**Comment by semireg** [comment]
Got it, thanks. Posted to http://forums.adafruit.com/viewtopic.php?f=53&t=95480&p=479241&hilit=notify+characteristic#p479241
