### ISSUE TITLE
Adafruit_BLE::install_callback should not force _verbose to true

### ISSUE THREAD

**Issue by frankleonrose** [adafruit/Adafruit_BluefruitLE_nRF51#24]
When you turn verbose mode off, all is quiet except this method. Seems like inadvertent commit of debug code.

https://github.com/adafruit/Adafruit_BluefruitLE_nRF51/blob/master/Adafruit_BLE.cpp#L85

**Comment by hathach** [comment]
thank for reporting the issue, it is indeed legacy code for debugging :)
