### ISSUE TITLE
Make Adafruit_BluefruitLE_SPI an Arduino Stream

### ISSUE THREAD

**Issue by monteslu** [adafruit/Adafruit_BluefruitLE_nRF51#27]
Enhancement request:

This API is currently already close to Arduino's Stream as is:  https://www.arduino.cc/en/Reference/Stream

If it fully implemented it, we could do fun stuff like plugging it into Firmata and have the uart service pipe data back and forth.

**Comment by ladyada** [comment]
we already have a firmata demo, btw

**Comment by monteslu** [comment]
Ooh nice!  Want :)

StandardFirmataBLE doesn't support it, so I was trying to get it to work on the Feather 32u4 Bluefruit.

I'm not seeing it anywhere, could you give a URL?

**Comment by ladyada** [comment]
https://learn.adafruit.com/bluefruit-le-connect-for-ios/library-and-config

**Comment by microbuilder** [comment]
I'm going to close this for now since Firmata exists, but if there is a compelling use case we can open this back up again.
